### ISSUE TITLE
Can it be used to build Raspbian images?

### ISSUE THREAD

**Issue by Pierre-Gilles** [lukechilds/dockerpi#2]
First, thanks for this amazing work ! 👏 

I'm the founder of [Gladys Assistant](https://github.com/GladysAssistant/Gladys/), it's an open-source home automation software which runs on a Raspberry Pi.

We distribute to our users a Raspbian image with Gladys pre-installed on it, and for now we build this image manually (we clone an empty raspbian on an ARMv6 Pi, then install Gladys, then backup the image and distribute the `.img`)

Does your Docker image can be used to build a .img file without having to use a Raspberry Pi? 

If yes, it's just amazing!

Btw, I just saw that you are working full-time on open-source and you're digital-nomad. I'm DN as well, and working part-time on open-source. Would love to chat with you, I followed you on Twitter, I'm [@pierregillesl](https://twitter.com/pierregillesl).

**Comment by lukechilds** [comment]
Thanks, Gladys looks like a cool project!

Regarding your question - I'm not sure but I would imagine so, yes.

Try:
- Downloading a fresh Raspbian image
- Booting it with `docker run -it -v /path/to/raspbian.img:/sdcard/filesystem.img lukechilds/dockerpi`
- Install Gladys
- Shut down
- Write `/path/to/raspbian.img` to an SD card
- Put SD card in a Raspberry Pi and see if it boots

If everything works as expected then `/path/to/raspbian.img` is your working image built without the requirement of a physical Pi.

You can probably automate this much more efficiently by just mounting the Raspbian image and writing your built binaries to it. No need to emulate a full Pi.

That would also be much safer incase you end up accidentally generating artefacts you don't users sharing such as PGP/SSH keys etc.

But this emulation method would definitely be a good improvement over your current method of requiring a physical Pi.

I'll close this issue for now but please report back how you get on if you try it!
