### ISSUE TITLE
Can we use Raspbian Jessie with this Docker

### ISSUE THREAD

**Issue by dragonBall561** [lukechilds/dockerpi#22]
I am wondering how to use Raspbian Jessie, not any earlier or later versions, with this docker. How would I do that?

- Angad

**Comment by hardillb** [comment]
Download the Jessie image, unzip it, and then pass it in as a volume described in the [Usage](https://github.com/lukechilds/dockerpi#usage) section of the README.md

**Comment by dragonBall561** [comment]
nvrmnd got desktop working in qemu it was really hard
