### ISSUE TITLE
bind-mount not working?

### ISSUE THREAD

**Issue by nathankopp** [lukechilds/dockerpi#23]
I'm trying to use a bind mount to access the host filesystem from within the emulated environment.

I added "--mount type=bind,source=/path/to/host/folder,target=/host_folder" to my command line.  Docker Hub is showing the mount when I inspect the running instance.  The host folder does exist.  No errors about the bind can be seen during startup.  However, the "/host_folder" target is not showing NOT show up inside the emulated system.

The host is MacOS 10.15.4

Is this supported? If so, what am I doing wrong?

**Comment by hardillb** [comment]
This won't work, the bind mount will mount the directory into the container, but there is nothing to then make that available to the VM that is running in the container.

**Comment by nathankopp** [comment]
Thanks. I did figure that out once I realized that Docker isn't running qemu directly, but rather Docker is running an Intel Linux vm, which is then running qemu with another Linux inside that.  Linux-inception.
