### ISSUE TITLE
Automate login and script in container

### ISSUE THREAD

**Issue by bjajoh** [lukechilds/dockerpi#40]
Hi,

I would like to automate the login and run stuff automated in the container.
However, I'm not exactly sure how.
I would be grateful if you can point me in the right direction!

Thanks for you help!

**Comment by bjajoh** [comment]
Never mind, just found that it is not possible.
https://github.com/lukechilds/dockerpi/issues/12

**Comment by kafeg** [comment]
Check this one pls: https://gist.github.com/kafeg/93d8057cf32e249d91da332449016eb4
